- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx 
      state: installed
  - name: enable nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
