- name: multiplay
  hosts: localhost
  become: yes
  tasks:
  - name: Play-1 task-1
    ansible.builtin.debug:
      msg: "Play-1 and Task-1"
  - name: Play-1 task-2
    ansible.builtin.debug:
      msg: "Play-1 and task-2"
- name: multiplay
  hosts: localhost
  become: yes
  tasks:
  - name: Play-2 task-1
    ansible.builtin.debug:
      msg: "Play2 task1"
  - name: Play-2 task2
    ansible.builtin.debug:
      msg: "Play 2 task 2"              