- name: variables
  hosts: localhost
  vars:
    COURSE: "Terraform"
    Trainer: "SIVA"
    Duration: "15hrs"
  tasks:
  - name: Overridding
    vars:
      COURSE: "DEVOPS"
    ansible.builtin.debug:
      msg: "Hi,learning {{COURSE}}"    
  - name: Inheritance    
    ansible.builtin.debug:
      msg: "Hi learning {{COURSE}}"