- name: Vars from inventory
  hosts: localhost
  vars:
    TIMINGS: "08-Aug-2024"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi,we are learning {{COURSE}} {{TRAINER}} {{DURATION}} {{TIMINGS}} "

  