- name: conditions
  hosts: localhost
  become: no
  tasks:
  - name: check user
    ansible.builtin.command: id expense
    ignore_erros: true

  - name: msg
    ansible.builtin.debug:
      msg: "Helo"  

