- name: conditions
  hosts: localhost
  become: no
  tasks:
  - name: check user
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: print user info
    ansible.builtin.debug:
      msg: "{{USER.rc}}"  

  - name: msg
    ansible.builtin.debug:
      msg: "Helo"  

