- name: default values
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"
- name: upper cases
  hosts: localhost
  vars:
    greeting: "Hello , good morning"
  tasks:
  - name: Covert into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower cases
  hosts: localhost
  vars:
    greeting: "Hello, good morning"
  tasks:
  - name: Convert into lower cases
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"  

- name: Remove dups
  hosts: localhost
  vars:
  - numbers: [1,2,3,3,4,4,5,6,6]
  tasks:
  - name: remove dups
    ansible.builtin.debug:
      msg: "{{numbers | unique}}""
