- name: default values
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"
- name: upper cases
  hosts: localhost
  vars:
    greeting: "Hello , good morning"
  tasks:
  - name: Covert into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}""
