- name: default values
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"
- name: upper cases
  hosts: localhost
  vars:
    greeting: "Hello , good morning"
  tasks:
  - name: Covert into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower cases
  hosts: localhost
  vars:
    greeting: "Hello, good morning"
  tasks:
  - name: Convert into lower cases
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"  

- name: Remove dups
  hosts: localhost
  vars:
    numbers: [1,2,3,3,4,4,5,6,6]
  tasks:
  - name: remove dups
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"
- name: print min and max
  hosts: localhost
  vars:
    ages: [25,35,67,89]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "min:::{{ages | min}} max:{{ages | max}}"

- name: convert dict into items
  hosts: localhost
  vars: 
    my_dict:
      Course: ansibl
      Trainer: NNR
      Duration: 120hr
  taks:
  - name: Dictto items
    ansible.builtin.debug:
      msg: "Hello"
      


