- name: demo on loops
  hosts: web
  become: yes
  tasks:
  - name: install
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - {name: "mysql",state: "latest"}
    - {name: "nginx",state: "absent"}
    - {name: "postfix",state: "absent"}