# - name: ping the server
#   hosts: web 
#   become: no
#   tasks:
#   - name: ping the server
#     ansible.builtin.ping:

# - name: nginx 
#   hosts: web
#   become: yes
#   tasks:
#   - name: Install
#     ansible.builtin.dnf:
#       name: nginx
#       state: installed
#   - name: start service
#     ansible.builtin.service:
#       name: nginx
#       state: started
#       enabled: yes 

# - name: multiplay
#   hosts: localhost
#   become: no 
#   tasks:
#   - name: play-1 task-1
#     ansible.builtin.debug:
#       msg:  "Play-1,task-1"
#   - name: play-1 task-2
#     ansible.builtin.debug:
#       msg: "Play-1 , task-2"

# - name: multiplay
#   hosts: localhost
#   become: no 
#   tasks:
#   - name: play-2 task-1
#     ansible.builtin.debug:
#       msg:  "Play-1,task-1"
#   - name: play-2 task-2
#     ansible.builtin.debug:
#       msg: "Play-2 , task-2"

- name: variables
  hosts: localhost
  become: no 
  # vars:
  #   COURSE: "DEVOPS"
  #   TRAINER: "SIVA"
  vars_files:
    vars.yaml  
  tasks:
  - name: vars1 task
    # vars:
    #   COURSE: "DEVOPS1"
    ansible.builtin.debug:
      msg: "{{COURSE}} {{TRAINER}}"  

  # - name: vars2 play
  #   ansible.builtin.debug:
  #     msg: "{{COURSE}} {{TRAINER}}"       


 
